name: MuyeCustomStore
version: '${version}'
main: com.muye.muyecustomstore.MuyeCustomStore
author: Muye
depend:
  - Vault
  - PlayerPoints
softdepend:
  - PlaceholderAPI
commands:
  MuyeCustomStore:
    aliases: mcs
    description: "总指令"